language: java
notifications:
    email: false
jdk:
    - openjdk8
services:
    - docker
after_script:
    - "gem query --local | grep bundler >/dev/null || gem install bundler"
    - "export BUNDLE_GEMFILE=$PWD/docs/Gemfile"
    - "bundle config set path 'docs/_vendor/bundle'"
    - "bundle install"
    - "cd docs"
    - "rake travis"
env:
  global:
    secure: GwYDfj/JiE/x3Q9BaVlxNSODaidWWL75vjahnTP1XBaViydDSleF+dtLvA2iffSx7vdvQvh7Dr6F43kGwda8dUhahDHk1s3Gt5KFSPfN+urwZ023XoFYCANL/6ys9JR0Hpyz5bIE0F2jGpiD1UyQk3pK10ZuuVHmSD2jpSJLJpw=
